services:
  etl_pipeline:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: etl_pipeline
    restart: unless-stopped
    networks:
      - projet_12_custom_network
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: 172.88.0.8
      POSTGRES_PORT: 5432
      PYTHONUNBUFFERED: 1
    volumes:
      - etl_logs:/app/logs

networks:
  projet_12_custom_network:
    external: true

volumes:
  etl_logs:
